
# Configuracion del servidor
server.port=8080

# Configuracion de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/adoptar_db
spring.datasource.username=postgres
spring.datasource.password=adoptar_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Nombre de la aplicacion
spring.application.name=adoptar-backend

# JWT
jwt.secret=YWRvcHRhclNlY3JldEtleVBhcmFKV1RBdXRoZW50aWNhY2lvbkFwcDIwMjY=
jwt.expiration=604800000

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
